<a href="https://colab.research.google.com/github/arnaldorosentino/ExerciciosMBA_Parte2/blob/main/Aula_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteca Numpy

Biblioteca Python para Álgebra Linear:
https://numpy.org/doc/

In [1]:
lista1 = [1, 2, 3, 4]
lista2 = [1, 3, 5, 7]

lista1 + lista2


[1, 2, 3, 4, 1, 3, 5, 7]

In [1]:
import numpy as np

# Arrays

In [3]:
vetor1 = np.array(lista1)
vetor2 = np.array(lista2)

print(vetor1)

[1 2 3 4]


In [4]:
vetor1 + vetor2

array([ 2,  5,  8, 11])

In [ ]:
# Operações com arrays

In [5]:
vetor1 * vetor2

array([ 1,  6, 15, 28])

In [6]:
vetor1 / vetor2

array([1.        , 0.66666667, 0.6       , 0.57142857])

In [7]:
vetor1 - vetor2

array([ 0, -1, -2, -3])

In [8]:
vetor1**2

array([ 1,  4,  9, 16])

In [9]:
vetor1**vetor2

array([    1,     8,   243, 16384])

In [10]:
vetor1 > 3

array([False, False, False,  True])

In [11]:
vetor1[:2]

array([1, 2])

In [12]:
vetor1[2:]

array([3, 4])

In [ ]:
# dimensões de arrays

In [13]:
vetor1.shape

(4,)

In [17]:
matriz = np.array([ [2, 4], [3, 9], [1, 12] ])
matriz

array([[ 2,  4],
       [ 3,  9],
       [ 1, 12]])

In [18]:
matriz.shape

(3, 2)

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [22]:
np.ones(7, dtype = int)

array([1, 1, 1, 1, 1, 1, 1])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3).dot(np.eye(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
matriz1 = vetor1.reshape(2,2)
matriz2 = vetor2.reshape(2,2)
matriz1

array([[1, 2],
       [3, 4]])

In [28]:
#multiplicação de matriz -> método 1
matriz1.dot(matriz2)

array([[11, 17],
       [23, 37]])

In [29]:
#multiplicação de matriz -> método 2
matriz1 @ matriz2

array([[11, 17],
       [23, 37]])

In [30]:
#matriz inversa
np.linalg.inv(matriz1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [31]:
np.linalg.inv(matriz1) @ matriz1

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
# Exercício Proposto

In [34]:
X = np.array ([[1,12], [3,10], [2,11]])
X

array([[ 1, 12],
       [ 3, 10],
       [ 2, 11]])

In [36]:
y = np.array([[5], [4], [7]])
y

array([[5],
       [4],
       [7]])

In [ ]:
# b = ((X'X)^-1)X'y
# A' -> Transposta
# A^-1 -> Inversa

In [37]:
Xt = X.transpose()
Xt

array([[ 1,  3,  2],
       [12, 10, 11]])

In [38]:
Prod = Xt @ X
Prod

array([[ 14,  64],
       [ 64, 365]])

In [39]:
InvProd = np.linalg.inv(Prod)
InvProd

array([[ 0.35996055, -0.06311637],
       [-0.06311637,  0.01380671]])

In [41]:
b = InvProd @ Xt @ y
print(b)

[[-0.01282051]
 [ 0.48717949]]


In [3]:
# arange ->  O terceiro elemento indica o passo desejado
np.arange(0 , 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
#linspace -> O terceiro elemento indica a quantidade de elementos pretendidos
np.linspace(0, 11.15, 4)

array([ 0.        ,  3.71666667,  7.43333333, 11.15      ])

In [8]:
np.linspace(0, 10, 2, endpoint = False)

array([0., 5.])

In [9]:
np.linspace(0, 10, 2, endpoint = True)

array([ 0., 10.])

In [10]:
x = np.linspace(0, 100, 1001)
x

array([  0. ,   0.1,   0.2, ...,  99.8,  99.9, 100. ])

In [12]:
y = np.linspace(0, 100, 27)
y

array([  0.        ,   3.84615385,   7.69230769,  11.53846154,
        15.38461538,  19.23076923,  23.07692308,  26.92307692,
        30.76923077,  34.61538462,  38.46153846,  42.30769231,
        46.15384615,  50.        ,  53.84615385,  57.69230769,
        61.53846154,  65.38461538,  69.23076923,  73.07692308,
        76.92307692,  80.76923077,  84.61538462,  88.46153846,
        92.30769231,  96.15384615, 100.        ])

In [13]:
len(y)

27

In [14]:
y.shape

(27,)

In [15]:
y.reshape(9,3)

array([[  0.        ,   3.84615385,   7.69230769],
       [ 11.53846154,  15.38461538,  19.23076923],
       [ 23.07692308,  26.92307692,  30.76923077],
       [ 34.61538462,  38.46153846,  42.30769231],
       [ 46.15384615,  50.        ,  53.84615385],
       [ 57.69230769,  61.53846154,  65.38461538],
       [ 69.23076923,  73.07692308,  76.92307692],
       [ 80.76923077,  84.61538462,  88.46153846],
       [ 92.30769231,  96.15384615, 100.        ]])

In [16]:
y.reshape(3, 3, 3)

array([[[  0.        ,   3.84615385,   7.69230769],
        [ 11.53846154,  15.38461538,  19.23076923],
        [ 23.07692308,  26.92307692,  30.76923077]],

       [[ 34.61538462,  38.46153846,  42.30769231],
        [ 46.15384615,  50.        ,  53.84615385],
        [ 57.69230769,  61.53846154,  65.38461538]],

       [[ 69.23076923,  73.07692308,  76.92307692],
        [ 80.76923077,  84.61538462,  88.46153846],
        [ 92.30769231,  96.15384615, 100.        ]]])

In [18]:
# concatenate
vetor1 = np.array([1,2,3])
vetor2 = np.array([1,6,9])

np.concatenate([vetor1, vetor2])

array([1, 2, 3, 1, 6, 9])

In [19]:
vetor3 = np.concatenate([vetor1, vetor2, vetor1])

In [21]:
vetor3 = vetor3.reshape(3,3)
vetor3

array([[1, 2, 3],
       [1, 6, 9],
       [1, 2, 3]])

In [22]:
vetor3.mean()

3.111111111111111

In [23]:
# media das colunas
vetor3.mean(axis = 0)

array([1.        , 3.33333333, 5.        ])

In [24]:
# media das linhas
vetor3.mean(axis = 1)

array([2.        , 5.33333333, 2.        ])

In [25]:
# Desvio Padrão
vetor3.std()

2.5579698740491867

In [26]:
# minimo
vetor3.min()

1

In [27]:
# max
vetor3.min()

1

In [28]:
# soma
vetor3.sum()

28

In [29]:
# variância
vetor3.var()

6.543209876543211

In [30]:
# raiz
np.sqrt(vetor3.var())

2.5579698740491867

# Exercício Proposto

Refaça a função SimularCompletarAlbum da aula 10, substituindo, quando pertinente, por opções do numpy e compare a velocidade de execução
entre as duas abordagens