<a href="https://colab.research.google.com/github/arnaldorosentino/ExerciciosNumpy/blob/main/Aula_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Biblioteca Numpy

Biblioteca Python para Álgebra Linear:
https://numpy.org/doc/

In [1]:
lista1 = [1, 2, 3, 4]
lista2 = [1, 3, 5, 7]

lista1 + lista2


[1, 2, 3, 4, 1, 3, 5, 7]

In [2]:
import numpy as np

# Arrays

In [3]:
vetor1 = np.array(lista1)
vetor2 = np.array(lista2)

print(vetor1)

[1 2 3 4]


In [4]:
vetor1 + vetor2

array([ 2,  5,  8, 11])

In [ ]:
# Operações com arrays

In [5]:
vetor1 * vetor2

array([ 1,  6, 15, 28])

In [6]:
vetor1 / vetor2

array([1.        , 0.66666667, 0.6       , 0.57142857])

In [7]:
vetor1 - vetor2

array([ 0, -1, -2, -3])

In [8]:
vetor1**2

array([ 1,  4,  9, 16])

In [9]:
vetor1**vetor2

array([    1,     8,   243, 16384])

In [10]:
vetor1 > 3

array([False, False, False,  True])

In [11]:
vetor1[:2]

array([1, 2])

In [12]:
vetor1[2:]

array([3, 4])

In [ ]:
# dimensões de arrays

In [13]:
vetor1.shape

(4,)

In [17]:
matriz = np.array([ [2, 4], [3, 9], [1, 12] ])
matriz

array([[ 2,  4],
       [ 3,  9],
       [ 1, 12]])

In [18]:
matriz.shape

(3, 2)

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [22]:
np.ones(7, dtype = int)

array([1, 1, 1, 1, 1, 1, 1])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(3).dot(np.eye(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
matriz1 = vetor1.reshape(2,2)
matriz2 = vetor2.reshape(2,2)
matriz1

array([[1, 2],
       [3, 4]])

In [28]:
#multiplicação de matriz -> método 1
matriz1.dot(matriz2)

array([[11, 17],
       [23, 37]])

In [29]:
#multiplicação de matriz -> método 2
matriz1 @ matriz2

array([[11, 17],
       [23, 37]])

In [30]:
#matriz inversa
np.linalg.inv(matriz1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [31]:
np.linalg.inv(matriz1) @ matriz1

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
# Exercício Proposto

In [34]:
X = np.array ([[1,12], [3,10], [2,11]])
X

array([[ 1, 12],
       [ 3, 10],
       [ 2, 11]])

In [36]:
y = np.array([[5], [4], [7]])
y

array([[5],
       [4],
       [7]])

In [ ]:
# b = ((X'X)^-1)X'y
# A' -> Transposta
# A^-1 -> Inversa

In [37]:
Xt = X.transpose()
Xt

array([[ 1,  3,  2],
       [12, 10, 11]])

In [38]:
Prod = Xt @ X
Prod

array([[ 14,  64],
       [ 64, 365]])

In [39]:
InvProd = np.linalg.inv(Prod)
InvProd

array([[ 0.35996055, -0.06311637],
       [-0.06311637,  0.01380671]])

In [41]:
b = InvProd @ Xt @ y
print(b)

[[-0.01282051]
 [ 0.48717949]]
